//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscore
    {
        public int id { get; set; }
        public bool hasWon { get; set; }
        public string player { get; set; }
        public Nullable<int> trials { get; set; }
        public Nullable<int> time_in_seconds { get; set; }
    }
}
